ads-mvc-ADS_v.1.4/SHUNetMVC.Web/Controllers/EmployeeKendoController.cs
using iText.Kernel.Events;
using iText.Kernel.Geom;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Borders;
using iText.Layout.Element;
using iText.Layout.Properties;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using SHUNetMVC.Abstraction.Model.Dto;
using SHUNetMVC.Abstraction.Services;
using SHUNetMVC.Infrastructure.Helpers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SHUNetMVC.Web.Controllers
{
    public class EmployeeKendoController : Controller
    {
        private IEmployeeKendoService _employeeKendoService;
        private IUserService _userService;
        private ICrudEmployeeKendoService _crudEmployeeKendoService;

        public EmployeeKendoController(IEmployeeKendoService employeeKendoService, IUserService userService, ICrudEmployeeKendoService crudEmployeeKendoService)
        {
            _employeeKendoService = employeeKendoService;
            _userService = userService;
            _crudEmployeeKendoService = crudEmployeeKendoService;
        }
        // GET: EmployeeKendo
        public async Task<ActionResult> Index()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                var currentUser = await _userService.GetCurrentUserInfo();
                if (currentUser.Roles == null)
                {
                    return View("NotAuthorized");
                }
                ViewBag.Roles = currentUser.Roles.FirstOrDefault().Value;
                return View();
            }
            return RedirectToAction("Index", "Home");
        }
        public async Task<ActionResult> ViewForm(int EmpId)
        {
            var data = await _employeeKendoService.GetById(EmpId);
            ViewBag.Mode = "View";
            return View("~/Views/EmployeeKendo/FormEmployeeKendo.cshtml",data);
        }
        public ActionResult CreateForm()
        {
            ViewBag.Mode = "create";
            return View("~/Views/EmployeeKendo/FormEmployeeKendo.cshtml");
        }
        public async Task<ActionResult> EditForm(int EmpId)
        {
            var data = await _employeeKendoService.GetById(EmpId);
            return View("~/Views/EmployeeKendo/FormEmployeeKendo.cshtml", data);
        }
        public async Task<JsonResult> GetAllEmployeeKendo([DataSourceRequest] DataSourceRequest request)
        {
            DataSourceResult result = new DataSourceResult();
            var EmpList = new List<EmployeeDto>();

            int total = await _employeeKendoService.GetTotalCount();

            if (request.Filters.Count > 0 || request.Sorts.Count > 0)
            {
                EmpList = await _employeeKendoService.GetAll(1, total);

                result = EmpList.ToDataSourceResult(request);
            }
            else
            {
                EmpList = await _employeeKendoService.GetAll(request.Page, request.PageSize);

                result.Data = EmpList;
                result.Total = total;
            }

            return Json(result, JsonRequestBehavior.AllowGet);

            //var data = await _employeeKendoService.GetAll(request.Page, request.PageSize);
            //return Json(data.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
        public async Task<ActionResult> ViewData(int EmpId)
        {
            var data = await _employeeKendoService.GetById(EmpId);
            return View(data);
        }

        [HttpPost]
        public async Task<ActionResult> Create([DataSourceRequest] DataSourceRequest request, EmployeeDto model)
        {
            try
            {
                //await _employeeKendoService.Save(model);
                await _crudEmployeeKendoService.Create(model);
                var response = new
                {
                    Success = true

                };

                return Json(response);
            }
            catch (Exception ex)
            {
                var response = new
                {
                    Success = false
                };

                return Json(response);
            }
        }

        [HttpPost]
        public async Task<ActionResult> Update([DataSourceRequest] DataSourceRequest request, EmployeeDto model)
        {
            try
            {
                await _crudEmployeeKendoService.Update(model);
                var response = new
                {
                    Success = true
                };

                return Json(response);
            }
            catch (Exception ex)
            {
                var response = new
                {
                    Success = false
                };

                return Json(response);
            }
        }

        public async Task<ActionResult> ExportPdf(int EmpId)
        {
            var data = await _employeeKendoService.GetById(EmpId);
            using (MemoryStream workStream = new MemoryStream())
            {
                PdfWriter writer = new PdfWriter(workStream);
                PdfDocument pdfDoc = new PdfDocument(writer);
                pdfDoc.SetDefaultPageSize(PageSize.A4);
                Document document = new Document(pdfDoc);
                float[] columnWidths = { 1f, 2f }; // 2 columns with widths in proportion
                Table table = new Table(UnitValue.CreatePercentArray(columnWidths));
                string imagePath = Server.MapPath("~/Assets/PHE_Logo_Color.png");
                document.SetMargins(80, 50, 50, 50);
                // Add the header event handler
                HeaderEventHandler headerHandler = new HeaderEventHandler("", imagePath);
                pdfDoc.AddEventHandler(PdfDocumentEvent.START_PAGE, headerHandler);
                pdfDoc.AddEventHandler(PdfDocumentEvent.END_PAGE, new FooterEventHandler());

                // Create PDF content
                document.Add(new Paragraph($"Employee Name : {data.EmpName}"));


                // Add the table to the document
                document.Add(table);
                document.Close();
                pdfDoc.Close();

                byte[] byteInfo = workStream.ToArray();
                return File(byteInfo, "application/pdf", "ExportedPdf.pdf");
            }
        }


        [HttpPost]
        public async Task<ActionResult> DeleteEmployeeKendo([DataSourceRequest] DataSourceRequest request, EmployeeDto employee)
        {
            if (employee != null && ModelState.IsValid)
            {
                await _employeeKendoService.DeleteEmployee(employee.EmpId);
            }
            return Json(new[] { employee }.ToDataSourceResult(request, ModelState));
        }
    }
}

ads-mvc-ADS_v.1.4/SHUNetMVC.Web/Views/EmployeeKendo/FormEmployeeKendo.cshtml
    @model  SHUNetMVC.Abstraction.Model.Dto.EmployeeDto
@{
    ViewBag.Title = "Form Employee Kendo";
    var isEdit = ViewBag.Mode == "View";
}
<br />
<div class="container" style="float: inline-start; padding: 0 2%; max-width: 100%">
    <div style="text-align:left">
        <span class="fa-solid fa-chevron-left" style="cursor: pointer;" onclick="redirectIndex()"> <strong>Back</strong></span>
    </div>
    <br />
    <h2>
        @ViewBag.Title
    </h2>
    <div class="border-bottom" style="margin-bottom: 1%;"></div>
    <form id="employeeForm">
        <div class="row mb-3">
            <div class="col-sm-6">
                <label>Employee ID <span style="color: #F50707;">*</span></label>
                @Html.Kendo().TextBox().Name("EmpId").Readonly(true)
            </div>
            <div class="col-sm-6">
                <label>Employee Name <span style="color: #F50707;">*</span></label>
                @Html.Kendo().TextBox().Name("EmpName")
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-sm-6">
                <label>Employee Position <span style="color: #F50707;">*</span></label>
                @Html.Kendo().TextBox().Name("EmpPosition")
            </div>
            <div class="col-sm-6">
                <label>Department <span style="color: #F50707;">*</span></label>
                @(Html.Kendo().DropDownList()
                .Name("DepartementId")
                .DataTextField("DepartementName")
                .DataValueField("DepartementId")
                .DataSource(source =>
                {
                    source.Read(read =>
                    {
                        read.Action("GetDepartment", "Common");
                    });
                })
                )
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-sm-6">
                <label>Birth Date <span style="color: #F50707;">*</span></label>
                @(Html.Kendo().DatePicker().Name("Birthdate").Format("dd MMM yyyy "))
            </div>
            <div class="col-sm-6">
                <label>Organization Unit Id <span style="color: #F50707;">*</span></label>
                @(Html.Kendo().NumericTextBox().Name("OrgUnitId").Min(0))
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-sm-6">
                <label>Score <span style="color: #F50707;">*</span></label>
                @(Html.Kendo().NumericTextBox().Name("Score").Min(0))
            </div>
            <div class="col-sm-6">
                <label>Address <span style="color: #F50707;">*</span></label>
                @(Html.Kendo().TextBox().Name("Address"))
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-sm-6">
                <label>City <span style="color: #F50707;">*</span></label>
                @(Html.Kendo().TextBox().Name("City"))
            </div>
            <div class="col-sm-6">
                <label>Postal Code <span style="color: #F50707;">*</span></label>
                @(Html.Kendo().TextBox().Name("PostalCode"))
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-sm-6">
                <label>Phone <span style="color: #F50707;">*</span></label>
                @(Html.Kendo().TextBox().Name("Phone"))
            </div>
            <div class="col-sm-6">
                <label>Email <span style="color: #F50707;">*</span></label>
                @(Html.Kendo().TextBox().Name("Email"))
            </div>
        </div>
        <div class="border-bottom" style="margin-bottom: 1%;"></div>
        <div style="text-align:right">
            @if (isEdit)
            {
                <button class="btn btn-primary" type="button" style="border-radius: 4px;" onclick="update()">Update</button>
            }
            else
            {
                <button class="btn btn-outline-primary" type="button" style="border-radius: 4px;" onclick="save()">Save as Draft</button>
            }
        </div>
    </form>
    
</div>
<script>
    function redirectIndex() {
        var url = '@Url.Action("Index", "EmployeeKendo")';
        window.location.href = url;
    }
    function save() {
        let data = $('#employeeForm').serialize();
        var url = '@Url.Action("Create", "EmployeeKendo")';
        $.ajax({
            type: "POST",
            url: url,
            data: data,
            success: function (response) {
                if (response.Success == true) {
                    alert("OK")
                } else {

                }
            }
        })
    }
    function update() {
        let data = $('#employeeForm').serialize();
        var url = '@Url.Action("Update", "EmployeeKendo")';
        $.ajax({
            type: "POST",
            url: url,
            data: data,
            success: function (response) {
                if (response.Success) {
                    alert("Employee updated successfully");
                } else {
                    alert("Error updating employee");
                }
            }
        });
    }
</script>

ads-mvc-ADS_v.1.4/SHUNetMVC.Web/Views/EmployeeKendo/Index.cshtml
<style>
    .k-grid .k-grid-search {
        display: flex;
        margin-left: auto;
        margin-right: 0;
        width: max-content;
    }

    .k-grid-header, .k-grid-header .k-header {
        background-color: #D6E7F3;
        border-color: #A5CAE6;
    }

    .k-grid-toolbar {
        background-color: transparent;
        border-color: transparent;
    }

    .k-button-text {
        background-color: transparent;
    }

    .k-button-solid-base {
        border-radius: 4px;
    }

    .k-grid.k-grid-display-block {
        display: block;
        border: none;
    }

    .btn.disabled, .btn:disabled, fieldset:disabled .btn {
        color: #ADB5BD;
        pointer-events: none;
        background-color: #E9ECEF;
        border-color: #ADB5BD;
        cursor: not-allowed;
    }

    .k-button-md.k-icon-button > .k-button-icon {
        min-width: 1.5rem;
        min-height: 0rem;
    }
</style>
<div class="header-page">
    Master Data Employee Kendo
</div>
<br />
<div class="container" style=" float: inline-start; padding: 0 2%; max-width: 100%">
    <button class="btn btn-primary" style="border-radius: 4px; float: right" onclick="directToCreate()"><span><i class="fa fa-plus"></i>&nbsp;Add New Employee</span></button>
</div>
<br />
<div class="container" style=" float: inline-start; padding: 0 2%; max-width: 100%">
    <br />
    <div style="float: inline-start; width: 100%">
        @(Html.Kendo().Grid<SHUNetMVC.Abstraction.Model.Dto.EmployeeDto>()
    .Name("gridEmployeeKendo")
    .Columns(columns => {
        columns.Command(command =>
        {
            command.Custom("view").Click("onClickViewData").Text(" ").IconClass("fas fa-eye").HtmlAttributes(new { @class = "btn btn-sm btn-outline-primary" });
            command.Custom("editData").Click("onClickView").Text(" ").IconClass("fas fa-pencil").HtmlAttributes(new { @class = "btn btn-sm btn-outline-success" });
            //command.Custom("delete").Click("onClickDelete").Text(" ").IconClass("fas fa-trash").HtmlAttributes(new { @class = "btn btn-sm btn-outline-danger delete-button" });


        })
            .Title("Action").HeaderHtmlAttributes(new { style = "text-align:center;" }).HtmlAttributes(new { style = "text-align: center;" }).Width(170).Sticky(true);
        columns.Command(command => { command.Destroy(); }).Width(150);
        columns.Bound(p => p.EmpId).Hidden();
        columns.Bound(p => p.EmpName).Width(150).Title("Name");
        columns.Bound(p => p.EmpPosition).Width(150).Title("Position");
        columns.Bound(p => p.DepartementName).Width(200).Title("Department");
        columns.Bound(p => p.Birthdate).Width(150).Format("{0:dd MMM yyyy}");

        columns.Bound(p => p.OrgUnitId).Width(150);
        columns.Bound(p => p.Score).Width(100);
        columns.Bound(p => p.City).Width(150);
        columns.Bound(p => p.Address).Width(150);
        columns.Bound(p => p.PostalCode).Width(150);
        columns.Bound(p => p.Phone).Width(150);
        columns.Bound(p => p.Email).Width(250);
        //columns.Command(command =>
        //{
        //    command.Custom("viewData").Click("onClickViewData").Text(" ").IconClass("fa-solid fa-file").HtmlAttributes(new { @class = "btn btn-sm btn-outline-primary" });
        //})
        //    .Title("View").HeaderHtmlAttributes(new { style = "text-align:center;" }).HtmlAttributes(new { style = "text-align: center;" }).Width(100);
    })
    .ToolBar(t => { t.Search(); t.Excel(); })
    .Pageable(pageable => pageable.PageSizes(true))
    .Sortable()
    .Scrollable()
    .Filterable()
    .Resizable(resizable => resizable.Columns(true))
    .Height(580)
    .DataSource(dataSource => dataSource
        .Ajax()
        .PageSize(10)
        .Read(read => read.Action("GetAllEmployeeKendo", "EmployeeKendo"))
        .Destroy(destroy => destroy.Action("DeleteEmployeeKendo", "EmployeeKendo"))
         .Model(model =>
         {
             model.Id(Z => Z.EmpId);
             model.Field(Z => Z.EmpId).Editable(true);
         })
     )
    .Events(events => events.DataBound("onDataBound"))
)
    </div>
</div>
<script>

    function onClickView(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        let EmpId = dataItem.EmpId;
        
        var url = '@Url.Action("ViewForm", "EmployeeKendo", new { EmpId = "id"})'.replace("id", EmpId);

        window.location.href = url;
    }
    function onClickViewData(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        let EmpId = dataItem.EmpId;
        var url = '@Url.Action("ViewData", "EmployeeKendo", new { EmpId = "id" })'.replace("id", EmpId);
        window.location.href = url;
    }
    function onClickEdit(e) {
        debugger;
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        let EmpId = dataItem.EmpId;
        var url = '@Url.Action("EditForm", "EmployeeKendo", new { EmpId = "id" })'.replace("id", EmpId);
        window.location.href = url;
    }
    function onClickDelete(e) {
        //e.preventDefault();

        //debugger;

        //var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        //alert("Custom command clicked for " + dataItem.EmpName);

        //    if (confirm("Apakah Anda yakin ingin menghapus data ini?")) {
        //        grid.removeRow(dataItem);
        //    }


        // Add your custom command logic here
    }
    function onDataBound(e) {
        var grid = this;
        grid.tbody.find(".k-button.delete-button").each(function () {
            var dataItem = grid.dataItem($(this).closest("tr"));

            if (dataItem.EmpPosition === "Analyst") {
                $(this).prop("disabled", true); // Disable the button
            }
        });
    }
    function directToCreate() {
        var url = '@Url.Action("CreateForm", "EmployeeKendo")';
         window.location.href = url;
    }
</script>

ads-mvc-ADS_v.1.4/SHUNetMVC.Web/Views/EmployeeKendo/ViewData.cshtml
@model  SHUNetMVC.Abstraction.Model.Dto.EmployeeDto
@{
    ViewBag.Title = "View Data";
}

<div style="text-align:left;margin:10px">
    <span class="fa-solid fa-chevron-left" style="cursor: pointer;" onclick="redirectIndex()"> <strong>Back</strong></span>
</div>
<br />

<div class="header-page">
    Employee Information
</div>
<br />
<div class="container">
    <div>
        <a class="btn btn-outline-dark" style="border-radius: 4px; float: right" href="@Url.Action("ExportPdf", "EmployeeKendo", new { EmpId = Model.EmpId})"><span><i class="fa-solid fa-file-pdf"></i>&nbsp;Export Pdf</span></a>
    </div>
    <br />
    <br />
    <div class="border-bottom" style="margin-bottom: 1%;"></div>
    <div class="row">
        <div class="col-sm-2">
            <label>Employee Name</label>
        </div>
        <div class="col-sm-10">
            : @Model.EmpName
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2">
            <label>Employee Position</label>
        </div>
        <div class="col-sm-10">
            : @Model.EmpPosition
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2">
            <label>Departement</label>
        </div>
        <div class="col-sm-10">
            : @Model.DepartementName
        </div>
    </div>
    <br />
    <div class="border-bottom" style="margin-bottom: 1%;"></div>
</div>

<script>
     function redirectIndex() {
     var url = '@Url.Action("Index", "EmployeeKendo")';
     window.location.href = url;
 }
</script>